//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSWeatherApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSWeatherApp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weather.
        /// </summary>
        internal static string CurrentWeather {
            get {
                return ResourceManager.GetString("CurrentWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weather Details.
        /// </summary>
        internal static string CurrentWeatherDetails {
            get {
                return ResourceManager.GetString("CurrentWeatherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current weather on your location.
        /// </summary>
        internal static string Currentweatherforyourlocation {
            get {
                return ResourceManager.GetString("Currentweatherforyourlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Forecast Details.
        /// </summary>
        internal static string DailyForecastDetails {
            get {
                return ResourceManager.GetString("DailyForecastDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Forecast Weather.
        /// </summary>
        internal static string DailyForecastWeather {
            get {
                return ResourceManager.GetString("DailyForecastWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string Donthaveanaccount {
            get {
                return ResourceManager.GetString("Donthaveanaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter City Name.
        /// </summary>
        internal static string Entercityname {
            get {
                return ResourceManager.GetString("Entercityname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        internal static string Forecast {
            get {
                return ResourceManager.GetString("Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Forecast.
        /// </summary>
        internal static string HourlyForecast {
            get {
                return ResourceManager.GetString("HourlyForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Forecast Details.
        /// </summary>
        internal static string HourlyForecastDetails {
            get {
                return ResourceManager.GetString("HourlyForecastDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Temperature.
        /// </summary>
        internal static string MaxTemperature {
            get {
                return ResourceManager.GetString("MaxTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Temperature.
        /// </summary>
        internal static string MinTemperature {
            get {
                return ResourceManager.GetString("MinTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rain.
        /// </summary>
        internal static string NoRainFallback {
            get {
                return ResourceManager.GetString("NoRainFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        internal static string Rain {
            get {
                return ResourceManager.GetString("Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here.
        /// </summary>
        internal static string Registerhere {
            get {
                return ResourceManager.GetString("Registerhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current weather for your location.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the DS Weather!.
        /// </summary>
        internal static string WelcometotheDSWeatherApp {
            get {
                return ResourceManager.GetString("WelcometotheDSWeatherApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed.
        /// </summary>
        internal static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
    }
}
